development:
  adapter: postgresql
  encoding: unicode
  database: rails3-bootstrap-devise-cancan_development
  pool: 5
  username: lym
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: rails3-bootstrap-devise-cancan_test
  pool: 5
  username: lym
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rails3-bootstrap-devise-cancan_production
  pool: 5
  username: lym
  password:

cucumber:
  <<: *test